name: Publish to crates.io

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: brndnmtthws/rust-action@v1
        with:
          toolchain: nightly
      - run: cargo build
      - run: cargo test
      - run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish && sleep 20
        working-directory: codegen
      - run: cargo publish
